### ISSUE TITLE
Создать модель комментариев

### ISSUE THREAD

**Issue by md5orsha256** [md5orsha256/flask-hello-app#14]
# Задача
Создать модель комментариев.
У модели должны быть следующие поля:
 - id (уникальный идентификатор, целочисленный)
 - comment (содержимое комментария, тест, максимальная длина 2000 символов)
 - author (Автор комментария, строка, максимальная длина 150 символов)
 - created_at (дата и время создания записи. Значение должно устанавливаться автоматически, при добавления записи)

Модель должна иметь отношение один-ко-многим с моделью статей.

Для создания в бд таблицы для данной модели должна быть создана миграция

_Количество бонусных баллов: +0.1_

**Comment by iasman312** [comment]
Я)

**Comment by md5orsha256** [comment]
@iasman312 вы будете делать или задачу можно отдать другому желающему?

**Comment by iasman312** [comment]
Да, можно другому отдать)

**Comment by nrbksv** [comment]
+
