### ISSUE TITLE
Реализовать добавление комментария

### ISSUE THREAD

**Issue by md5orsha256** [md5orsha256/flask-hello-app#15]
# Задача
Реализовать функционал создания комментария
Создать форму для комментария (поля: комментарий и автор. см. задачу #14 ).
На странице детального просмотра статьи добавить форму добавления комментария
Унифицировать шаблон с формой добавления статьи таким образом, чтобы его можно было использовать со статьёй и комментарием. Получившийся шаблон перенести по пути `src/templates/partial/form.html`

# Критерий приёмки
Когда я захожу на страницу детального росмотра статьи - я должен увидеть форму добавления статьи с полями для ввода комментария и автора. После заполнения данных полей -  я должен попасть на страницу детального просмотра статьи, а комментарий добавиться в базу данных

_Количество бонусных баллов: +0.3_

**Comment by nrbksv** [comment]
+
