### ISSUE TITLE
Реализовать функционал редактирования статьи

### ISSUE THREAD

**Issue by md5orsha256** [md5orsha256/flask-hello-app#3]
# Задача
Реализовать редактирование статей
Для этого требуется:
 * Реализовать представление, которое должно обрабатывать следующие методы:
      - `GET` - в ответ на запрос клиент должен увидеть форму редактирования статьи. Все заполненные ранее поля должны быть подставлены в соответсвующие поля формы (сделать это можно передав нужные значения в kwargs в конструктор формы, например: `form = ArticleForm(title='article title')`)
     - `POST` - в ответ на запрос указанная статья должна быть отредактирована, а пользователь перенаправлен на страницу детального просмотра статьи
 * Перед тем, как статья будет сохранена требуется проверить на то, валидны ли данные (все валидации для создания статьи актуальны и для редактирования)
 * Реализовать шаблон редактирования статьи. Форму использовать ту же, что и для создания статьи (Задача #2 ).
 * На старнице детального просмотра статьи добавить ссылку (стилизовать требуется под кнопку) на редактирование статьи

# Критерии приёмки
Открыв страницу детального просмотра любой из статей я должен увидеть кнопку "Редактировать статью". После нажатия на которую я должен увидеть форму редактирования статьи, поля которой должны быть заполнены текущими значениями соответствующих полей.
Отредактировав значения полей и нажав на кнопку "Сохранить" я должен попасть на страницу детального просмотра статьи.
Значения полей статьи должны быть изменены и соответствовать тем, что я ввёл в форму на предыдущем шаге.
Если в форме я ввожу невалидные данные - после нажатия на кнопку сохранить я должен опять увидеть форму со значениями полей, что я ввёл до отправки и соответствующими сообщениями об ошибке(ах)
Если я введу юрл, ведущий на страницу редактирования, но указав `id` статьи, которой не существует - я должен получить ошибку 404

_Количество бонусных баллов: +0.2_

**Comment by nrbksv** [comment]
+

**Comment by md5orsha256** [comment]
продано
