### ISSUE TITLE
Перенести меню навигации в базовый шаблон

### ISSUE THREAD

**Issue by md5orsha256** [md5orsha256/flask-hello-app#4]
# Задача
Перенести меню навигации в базовый шаблон. 
Предусмотреть возможность добавления элементов меню навигации в шаблонах, которые расширяют базовый шаблон.
Список элементов меню для каждой из страниц:
Страница | Элементы меню навигации
--- | --- 
Список статей | "Создать статью"
Детальный просмотр статьи | "Создать статью", "Все статьи"
Создание статьи | "Все статьи"

Добавление элементов меню на страницах должно быть выполнено с помощью блоков (`{% block block_name %}{% endblock block_name %}`)
Добавляемые элементы меню навигации не должны ломать разметку самого меню навигации или других элементов
Стилизация добавляемых элементов должна быть выдержана в соотвествии с меню навигации

# Критерии приёмки
* Зайдя на главную страницу (список просмотра статей), в меню навигации я должен увидеть элемент меню "Создать статью". Нажав на него - я должен перейти на страницу создания статьи
* Перейдя на страницу детального просмотра статьи я должен увидеть в меню навигации элементы меню "Создать статью" и "Все статьи". Нажав на первый - я должен попасть на страницу создания статьи, нажав на второй - на страницу списка статей
* Перейдя на страницу создания статей - я должен видеть в меню навигации элемент меню "Все статьи", нажав на который - я должен попасть на страницу списка статей

_Количество бонусных баллов: +0.1_

**Comment by nrbksv** [comment]
+
