### ISSUE TITLE
Изменить оформление списка задач

### ISSUE THREAD

**Issue by md5orsha256** [md5orsha256/flask-hello-app#5]
# Задача
Используя подключенные стили HTML-фреймвока [Twitter Bootstrap](https://getbootstrap.com/docs) изменить стилизацию главной страницы. Сделать отображение статей в виде [карточек](https://getbootstrap.com/docs/4.6/components/card/) или [списка](https://getbootstrap.com/docs/4.6/components/list-group/). Для каждой статьи должна быть возможность перейти на страницу детального просмотра (добавить кнопку для перехода или сделать элемент ссылкой, в зависимости от того, какой способ реализации будет выбран)
Для каждой статьи должно быть отображены следующие её поля: 
* Заголовок
* Автор

# Критерии приёмки
Перейдя на страницу просмотра статьи я должен увидеть список статей, где каждая статья должно выглядеть как карточка или элемент списка (см. скриншоты ниже). В списке должен быть отображён заголовок статьи и её автор. Также должно быть возможность перейти на страницу детального просмотра данной статьи.
Глядя на список статей я визуально могу выделить каждую из статей (статьи не в куче и визуально отделены одна от другой)

_Количество бонусных баллов: +0.1_

**Comment by nrbksv** [comment]
+

**Comment by md5orsha256** [comment]
@nrbksv не забудьте обновить форк, иначе потом будет конфликт, который будет не очень весело решать)
