### ISSUE TITLE
Избавиться от захардкоженных ссылок в проекте

### ISSUE THREAD

**Issue by md5orsha256** [md5orsha256/flask-hello-app#6]
# Задача
Заменить все захардкоженные ссылки в коде и шаблонах на генерируемые ссылки, используя [функцию](https://flask.palletsprojects.com/en/1.1.x/api/#flask.url_for) `url_for`

Ссылки должны быть заменены при редиректах, в экшэнах форм, в элементах меню навигации, ссылках на редактирование статей и тд.

#  Критерии приёмки
В коде не должно остаться ссылок на внутренние ресурсы проекта, которые указаны в виде строки (например: `<form action="/articles/create/">` или `redirect('/articles/')`). Все они должны быть заменены на результат вызова функции `url_for` (например: `redirect(url_for('article_index'))`)

_Количество бонусных баллов: +0.1_

**Comment by iasman312** [comment]
Я могу взять?

**Comment by md5orsha256** [comment]
Да, назанчил

**Comment by md5orsha256** [comment]
> Я могу взять?

@iasman312 кстати, у вас форк старый, до обновления структуры на вебинаре. Вам нужно обновить его, иначе возникнут конфликты

**Comment by md5orsha256** [comment]
чтобы получить баллы - напишете вашу фамилию здесь или мне  в телеграме

**Comment by iasman312** [comment]
Ибраимов

**Comment by md5orsha256** [comment]
@iasman312 в пулл-реквесте конфликт. обновите вашу версию форка)
