### ISSUE TITLE
Реализовать удаление статей

### ISSUE THREAD

**Issue by md5orsha256** [md5orsha256/flask-hello-app#8]
## Задача
Реализовать удаление статьи.
Удалённая статья должна пропасть из списка всех статей.
Кнопка удаление статьи должна быть расположена на странице детального просмотра статьи рядом с кнопкой редактирования статьи. Цвет кнопки должен быть красный.
При удалении статьи должно открыться [модальное окно Bootstrap](https://getbootstrap.com/docs/4.0/components/modal/) с сообщением "Вы действительно хотите удалить статью <ARTICLE_TITLE>", где <ARTICLE_TITLE> - заголовок статьи, под которым расположено две кнопки : "Да" (кнопка должна быть красной. Нажатие на неё удаляет статью) и "Отмена" (Синяя. нажатие на неё закрывает модальное окно без удаления статьи). После удаления перенаправить на страницу списка статей

## Критерии приёмки

Перейдя на страницу детального просмотра статьи я должен увидеть кнопку красного цвета "Удалить статью", нажав на которую я увижу модальное окно с надписью "Вы действительно хотите удалить статью <ARTICLE_TITLE>", где <ARTICLE_TITLE> - заголовок статьи. Также на модальном окне я должен увидеть две кнопки: Красная кнопка "Да" и Синяя  "Отмена". 

Если в модальном окне я нажму на кнопку "Да" - меня должно перенаправить на страницу списка статей, в котором не будет той статьи, на странице детального просмотра которой я находился на первом шаге. 

В случае, если в модальном окне  будет нажата кнопка "Нет" - модальное окно закроется, а я останусь на странице детального просмотра статьи, при этом статья не должна быть удалена

_Количество бонусных баллов: +0.2_

**Comment by nrbksv** [comment]
+
