### ISSUE TITLE
Перенести базовый шаблон в пакет src

### ISSUE THREAD

**Issue by md5orsha256** [md5orsha256/flask-hello-app#9]
# Задача
Создать директорию `src/templates` и переместить в неё базовый шаблон. Все шаблоны, имеющиеся в проекте требуется унаследовать от него

# Критерии приёмки

шаблон `src/articles/templates/base.html` должен быть перемещён по пути `src/templates/base.html`. Все шаблоны, расположенные в `src/articles/templates/` должны расширять шаблон  `src/templates/base.html`. После запуска приложения все страницы должны корректно отображаться

_Количество бонусных баллов: +0.1_

**Comment by iasman312** [comment]
Можно мне?
